yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'password_reset_form/',
        views.PasswordResetForm.as_view(),
        name='password_reset_form'
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name="Текст сообщения",
                            help_text="Обязательное поле,\
                             не должно быть пустым")
    pub_date = models.DateTimeField("date published", auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=True,
        null=True, related_name="posts",
        verbose_name="Автор",
        help_text="Выберите имя автора"
    )
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        blank=True,
        null=True, related_name="posts",
        verbose_name="Группа",
        help_text="Выберите название группы"
    )

    class Meta:
        ordering = ['-pub_date']
        default_related_name = 'posts'

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
        widgets = {
            'text': forms.Textarea(attrs={
                'class': 'form-control',
                'cols': 40,
                'rows': 10,
                'name': 'text'
            }),
            'group': forms.Select(attrs={
                'class': 'form-control',
                'name': 'tetx',
            }),
        }

    class Meta:
        model = Post
        fields = ('text', 'group')

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render, redirect

from posts.forms import PostForm
from yatube import settings

from .models import Group, Post, User


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, settings.POST_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    page_number = request.GET.get('page')
    post_list = Post.objects.filter(group=group)
    paginator = Paginator(post_list, settings.POST_COUNT)
    page_obj = paginator.get_page(page_number)
    context = {
        'title': f'Записи сообщества {slug}',
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    user_profile = get_object_or_404(User, username=username)
    user_posts = Post.objects.filter(author=user_profile)
    posts_count = user_posts.count()
    paginator = Paginator(user_posts, settings.POST_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'author': user_profile,
        'page_obj': page_obj,
        'count': posts_count,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    user_post = get_object_or_404(Post, pk=post_id)
    posts = Post.objects.filter(author_id=user_post.author_id)
    posts_count = posts.count()
    context = {
        'post': user_post,
        'posts_count': posts_count,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=request.user.username)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post.pk)
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post.pk)
    context = {
        'form': form,
        'post': post,
        'is_edit': True,
    }

    return render(request, 'posts/create_post.html', context)

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'


class PasswordResetForm(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/password_reset_form.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, меня зовут Славутин Леонид</h1>
<p>
  Расскажу немного о себе: На данный момент я студент 20 когорты 
  "Back-end разработчик на Python" на платформе Я.Практикум. 
  До этого самостоятельно изучал немного мануальное тестирование,
  пробовал себя в тестовых заданиях. Также знаком немного с автоматизированным 
  тестированием (End2End).
  Я, как можно увидеть из моего резюме, параллельно получил 2 высших образования 
  (инженер по ПТСДМ и экономист бизнес-администрировние). Дальше продолжил свою 
  деятельность в магистратуре и аспирантуре. У меня есть патент в соавторстве
  <a href="https://drive.google.com/file/d/1qX7CPf99umSmoRJtuLsrl9ewub_VTa5i/view?usp=sharing"> 
    на установку по нанесению полимерных покрытий</a>. 
  Мне очень нравится изучать что-то новое, поэтому я прошел 2 курса по математике 
  на портале EdX от двух университетов (Delft University of Technology, The University of Texas at Austin). 
  Также самостоятельно изучал немного Python, для написания desktop версии «Своя игра».
  Также хочу в скором времени написать игру-таполку на питоне через android-овский фреймворк.
</p>
{% endblock %} 

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею</h1>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья  
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  <article class="col-12 col-md-9">
    <p>На курсе я освоил пока базовый курс питона, django, html и sql (немножко)</p>
  </article>
</div>
{% endblock %} 

yatube/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180"
          href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32"
          href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16"
          href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}
        Title нету
      {% endblock %}
    </title>
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      <div class="container">
        {% block content %}
          Контент не подвезли :(
        {% endblock %}
      </div>  
    </main>
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}  
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
     <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
    <span style="color:red">Ya</span>tube
   </a>
   <ul class="nav nav-pills">
    {% with request.resolver_match.view_name as view_name %} 
    <li class="nav-item">              
      <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
         href="{% url 'about:author' %}"
      >
        Об авторе
      </a>
    </li>
    <li class="nav-item">              
      <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" 
         href="{% url 'about:tech' %}"
      >
      Технологии
      </a>
    </li>
    {% if user.is_authenticated %}
    <li class="nav-item">              
      <a class="nav-link {% if view_name  == 'users:create' %}active{% endif %}" 
         href="{% url 'posts:post_create' %}"
      >
      Новая запись
      </a>
    </li>
    <li class="nav-item">              
      <a class="nav-link link-light" 
         href="{% url 'users:logout' %}"
      >
      Выйти
      </a>
    </li>
    <li>
    <a class="nav-link" 
    href="{% url 'posts:profile' user.username %}">Пользователь: {{ user.username }} </a>
    <li>
    {% else %}
    <li class="nav-item">              
      <a class="nav-link link-light" 
         href="{% url 'users:login' %}"
      >
      Войти
      </a>
    </li>
    <li class="nav-item">              
      <a class="nav-link link-light{% if view_name  == 'users:signup' %}active{% endif %}" 
         href="{% url 'users:signup' %}"
      >
      Регистрация
      </a>
    </li>
    {% endif %}
   </ul>
  {% endwith %} 
 </div>
</nav>
</header>

yatube/templates/includes/paginator.html
{% load static %}  
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
    {% if is_edit %}
    Редактирование поста
    {% else %}
    Новый пост
    {% endif %}
{% endblock %}
{% block header %}
    {% if is_edit %}
    Форма редактирования публикации
    {% else %}
    Форма добавления публикации 
    {% endif %}
{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Создать пост</div>
            <div class="card-body">
                {% for error in form.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                {% endfor %}
                {% if is_edit %}
                <form action="{% url 'posts:post_edit' post.id %}" method="post">
                {% else %}
                <form action="{% url 'posts:post_create' %}" method="post">
                {% endif %}
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                            <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}
                                {% if field.field.required %}
                                <span class="required">*</span>
                                {% endif %}</label>
                    <div class="col-md-6">
                                {{ field }}
                                {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                    <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary" value="Save">
                                {% if is_edit %}
                                Сохранить
                                {% else %}
                                Добавить публикацию
                                {% endif %}
                            </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества
{% endblock %}
{% block content %}
  <h1>{{ group }}</h1>
  <h3>Описание группы: </h3>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }} 
        <a href="{% url 'posts:profile' post.author %}">
          все посты пользователя
        </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    </article>
    <p>{{ post.text|linebreaksbr| truncatewords:30 }}</p>
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor%}
  {% include 'includes/paginator.html' %}
{% endblock %}2

yatube/templates/posts/includes/paginator.html
{# templates/posts/includes/paginator.html #}

{# Отрисовываем навигацию паджинатора только если
все посты не помещаются на первую страницу #}
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      <li>
        Дата публикации: {{ post.pub_date|date:"d M Y" }}
      </ul>
    </p>{{ post.text|linebreaksbr }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
    {% if post.group %}  
    <p>
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    </p>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor%}
  {% include 'includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Пост: {{ post.text|truncatewords:30 }}
{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d M Y" }}
        </li>
        <li class="list-group-item">
          Группа:
          {% if post.group is not None %}  
          {{ post.group.title }}       
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif %}
       </li>
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span>{{ posts_count }}</span>
        </li>
       <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">
            Все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>
        {{ post.text|linebreaksbr }}
      </p>
      {% if post.author == request.user %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
          Редактировать пост
        </a>
      {% endif %}
    </article>
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Профайл пользователя {{ user.username }}
{% endblock %}
{% block content %}
<h1>Все посты пользователя {{ user.username }}  </h1>
      <h3>Всего постов: {{ count }} </h3>  
  {% for post in page_obj %}   
  <div class="container py-5">        
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d.m.Y"}} 
          </li>
        </ul>
        <p>
          {{ post.text|linebreaksbr| truncatewords:30 }}
        </p>
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
      </article>
        {% if post.group is not None %}        
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}         
      <hr>
      {% include 'includes/paginator.html' %}
  </div>
  {% endfor%}   
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> 
    </div> 
  </div> 
</div> 
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет!</h1>
<p>
  Пока эта страница в разработке :С
  Но ты можешь пока посмотреть <a href="https://www.youtube.com/watch?v=5qap5aO4i9A"> 
  короткий видос</a>.
  Когда досмотришь, мы уже все сделаем:)
</p>
{% endblock %} 

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}